name: urban-occupants
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy=1.12.1
  - pandas=0.19.2
  - matplotlib=2.0.1
  - seaborn=0.7.1
  - sqlalchemy=1.1.9
  - geopandas=0.2.1
  - ipython=5.3.0
  - ipykernel=4.6.1
  - ipywidgets=6.0.0
  - requests=2.13.0
  - requests-cache=0.4.12
  - xlrd=1.0.0
  - pandoc=1.19.2.1
  - pytest=3.0.7
  - pyyaml=3.12
  - pip:
      - git+git://github.com/riccardoscalco/Pykov@master
      - git+git://github.com/timtroendle/people@develop
      - git+git://github.com/timtroendle/pytus2000@v0.5.0
      - ./urbanoccupants/
      - pandoc-tablenos
      - pandoc-fignos
