name: ktp-paper
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy=1.12.*
  - pandas=0.19.2
  - matplotlib=2.0.0
  - seaborn=0.7.1
  - sqlalchemy=1.1.5
  - geopandas=0.2.1
  - ipython=5.3.0
  - ipykernel=4.5.2
  - ipywidgets=6.0.0
  - requests=2.13.0
  - requests-cache=0.4.12
  - xlrd=1.0.0
  - pandoc
  - pip:
      - git+git://github.com/riccardoscalco/Pykov@master
      - git+git://github.com/timtroendle/people@develop
