metabolic-heat-gain-active: 140
metabolic-heat-gain-passive: 70
metabolic-ratio-child: 0.75
people-features:
    - ECONOMIC_ACTIVITY
household-features:
    - PSEUDO
time-step-size-minutes: 10
start-time: 2005-01-07 00:00
spatial-resolution: WARD
number-processes: 4
java-heap-size: 12
heat-mass-capacity: 16500000
heat-transmission: 200
max-heating-power: 10000
initial-temperature: 22
conditioned-floor-area: 100
heating-control-strategy: PRESENCE_TRIGGERED
number-time-steps: 288
set-point-while-home: 22
set-point-while-asleep: 18
wake-up-time: '07:00'
leave-home-time: '08:30'
come-home-time: '18:00'
bed-time: '22:00'
log-thermal-power: True
log-temperature: False
log-activity: False
reweight-to-full-week: True
